app = "my-school-society"
primary_region = "iad"

[build]
  [build.args]
    PYTHON_VERSION = "3.11"

[env]
  SUPABASE_URL = "https://hnszltswipxiqurkwydm.supabase.co"
  SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhuc3psdHN3aXB4aXF1cmt3eWRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc1NTEyODcsImV4cCI6MjA5MzEyNzI4N30.JsSgMXE9JMqJAAZd-riwrr-D-5MURL6WCfuNTrAtoWU"
  SECRET_KEY = "django-insecure-twarvis-school-key-2024"
  ADMIN = "true"
  DEBUG = "False"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
